/*
@TargetNode='localhost'
@GeneratedBy=AzurePolicyGuestConfiguration
@GenerationDate=02/14/2019 10:00:00
@GenerationHost=AzurePolicyGuestConfiguration
*/

instance of MSFT_RegistryResource as $MSFT_RegistryResource1ref
{
ResourceID = "[Registry]Registry(POL): HKLM:\\Software\\Policies\\Microsoft\\WindowsFirewall\\PublicProfile\\EnableFirewall";
 ValueName = "EnableFirewall";
 Key = "HKLM:\\Software\\Policies\\Microsoft\\WindowsFirewall\\PublicProfile";
 SourceInfo = "::1::66::Registry";
 ValueType = "DWord";
 ModuleName = "GuestConfiguration";
 ValueData = {
    "1"
};
 ModuleVersion = "1.0.0.0";

 ConfigurationName = "WindowsFirewallEnabled";

};
instance of OMI_ConfigurationDocument


                    {
 Version="2.0.0";
 

                        MinimumCompatibleVersion = "1.0.0";
 

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};
 

                        Author="AzurePolicyGuestConfiguration";
 

                        GenerationDate="02/14/2019 10:00:00";
 

                        GenerationHost="AzurePolicyGuestConfiguration";
 

                        Name="WindowsFirewallEnabled";


                    };
