[ClassVersion("1.0.0.0")] 
class Reason
{
    [Read] String Phrase;
    [Read] String Code;
};

[ClassVersion("1.0.0.0"), FriendlyName("gcInSpec")]
class gcInSpec : OMI_BaseResource
{
    [Key, Description("Name of the InSpec profile")] String name;
    [Write, Description("The version of InSpec that is expected to be installed")] String version[];
    [Read, Description("Compliance status returned from InSpec")] Boolean status;
    [Read, EmbeddedInstance("Reason")] String Reasons[];
};